@startuml
企业微信主页面 -> 添加成员页面 : 点击添加成员
企业微信主页面 -> 通讯录页面 : 点击通讯录
通讯录页面 -> 企业微信主页面 : 点击主页
通讯录页面 -> 添加部门弹窗 : 点击添加部门
添加部门弹窗 -> 通讯录页面 : 1、添加部门信息；2、确定
通讯录页面 -> 通讯录页面 : 获取部列表信息
通讯录页面 -> 添加成员页面 : 点击添加成员
添加成员页面 -> 通讯录页面 : 1、添加成员信息；2、保存
通讯录页面 -> 通讯录页面 : 获取成员列表信息
企业微信主页面 -> 导入通讯录页面 : 点击导入通讯录
通讯录页面 -> 导入通讯录页面 : 1、点击批量导入；2、点击文件导入
导入通讯录页面 -> 通讯录页面 : 1、下载模板；2、填写模板信息；3、上传文件；4、点击前往查看
通讯录页面 -> 通讯录页面 : 获取通讯录列表信息
@enduml